
/*
 * PLEASE DON'T EDIT
 *
 * This file was automatically generated by
 * ./cpu/stm32/dist/irqs/gen_irqs.py
 */

#ifndef IRQS_F4_H
#define IRQS_F4_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined(STM32F401xC)
#define CPU_IRQ_NUMOF                   (85U)
#elif defined(STM32F401xE)
#define CPU_IRQ_NUMOF                   (85U)
#elif defined(STM32F405xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F407xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F410Cx)
#define CPU_IRQ_NUMOF                   (98U)
#elif defined(STM32F410Rx)
#define CPU_IRQ_NUMOF                   (98U)
#elif defined(STM32F410Tx)
#define CPU_IRQ_NUMOF                   (98U)
#elif defined(STM32F411xE)
#define CPU_IRQ_NUMOF                   (86U)
#elif defined(STM32F412Cx)
#define CPU_IRQ_NUMOF                   (97U)
#elif defined(STM32F412Rx)
#define CPU_IRQ_NUMOF                   (97U)
#elif defined(STM32F412Vx)
#define CPU_IRQ_NUMOF                   (97U)
#elif defined(STM32F412Zx)
#define CPU_IRQ_NUMOF                   (97U)
#elif defined(STM32F413xx)
#define CPU_IRQ_NUMOF                   (102U)
#elif defined(STM32F415xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F417xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F423xx)
#define CPU_IRQ_NUMOF                   (102U)
#elif defined(STM32F427xx)
#define CPU_IRQ_NUMOF                   (91U)
#elif defined(STM32F429xx)
#define CPU_IRQ_NUMOF                   (91U)
#elif defined(STM32F437xx)
#define CPU_IRQ_NUMOF                   (91U)
#elif defined(STM32F439xx)
#define CPU_IRQ_NUMOF                   (91U)
#elif defined(STM32F446xx)
#define CPU_IRQ_NUMOF                   (97U)
#elif defined(STM32F469xx)
#define CPU_IRQ_NUMOF                   (93U)
#elif defined(STM32F479xx)
#define CPU_IRQ_NUMOF                   (93U)
#endif

#ifdef __cplusplus
}
#endif

#endif /* IRQS_F4_IRQ_H */
