# liboqs
PKG_NAME = liboqs
PKG_URL = https://github.com/open-quantum-safe/liboqs.git
PKG_VERSION = af1b14e7b62bfa4fcc9cf7ed5cf0135bbd743cc4 # 0.5.0
PKG_LICENSE = MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(MAKE) -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base