# liboqs
PKG_NAME=liboqs
PKG_URL=https://github.com/open-quantum-safe/liboqs.git
PKG_VERSION=c0a550f7366a080653b436d041c66f155851911c # 0.5.0
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(MAKE) -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base