INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/include
INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/bindings
INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/build_tools
INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/src
INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/src/utils/crypto
INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/src/utils/threading
INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/src/schemes