INCLUDES += -I$(APPDIR)

INCLUDES += -I$(PKGDIRBASE)/libsafecrypto/include
INCLUDES += -I$(BINDIR)/pkg-build/libsafecrypto/bindings

ARCHIVES += $(RIOTBASE)/pkg/libsafecrypto/libsafecrypto.a
# ARCHIVES += $(BINDIR)/libsafecrypto.a

PSEUDOMODULES += libsafecrypto